// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vuelos.DAL.DataContext;

#nullable disable

namespace Vuelos.DAL.Migrations
{
    [DbContext(typeof(VuelosContext))]
    partial class VuelosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vuelos.Models.Entity.Flight", b =>
                {
                    b.Property<int>("IdFlight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFlight"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTransport")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("IdFlight");

                    b.HasIndex("IdTransport");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Vuelos.Models.Entity.Journey", b =>
                {
                    b.Property<int>("IdJourney")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJourney"));

                    b.Property<double>("BetterPriceBack")
                        .HasColumnType("float");

                    b.Property<double>("BetterPriceGo")
                        .HasColumnType("float");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdJourney");

                    b.ToTable("Journeys");
                });

            modelBuilder.Entity("Vuelos.Models.Entity.JourneyFlight", b =>
                {
                    b.Property<int>("JourneyId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<int>("NRuta")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("JourneyId", "FlightId", "NRuta", "Type");

                    b.HasIndex("FlightId");

                    b.ToTable("JourneyFlights");
                });

            modelBuilder.Entity("Vuelos.Models.Entity.Transport", b =>
                {
                    b.Property<int>("IdTransport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransport"));

                    b.Property<string>("FlightCarrier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTransport");

                    b.ToTable("Transports");
                });

            modelBuilder.Entity("Vuelos.Models.Entity.Flight", b =>
                {
                    b.HasOne("Vuelos.Models.Entity.Transport", "Transport")
                        .WithMany()
                        .HasForeignKey("IdTransport")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("Vuelos.Models.Entity.JourneyFlight", b =>
                {
                    b.HasOne("Vuelos.Models.Entity.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vuelos.Models.Entity.Journey", "Journey")
                        .WithMany("JourneyFlights")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Vuelos.Models.Entity.Journey", b =>
                {
                    b.Navigation("JourneyFlights");
                });
#pragma warning restore 612, 618
        }
    }
}
